export const slideItems = [
  {
    id: 1,
    img: '/Images/slide1.png',
    title: 'SUMMER SALE',
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: '#f5fafd',
  },
  {
    id: 2,
    img: '/Images/slide2.png',
    title: 'AUTUMN COLLECTION',
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: '#fcf1ed',
  },
  {
    id: 3,
    img: '/Images/slide3.png',
    title: 'POPULAR SALE',
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: '#fbf0f4',
  },
];

export const categories = [
  {
    id: 1,
    img: 'https://images.pexels.com/photos/5886041/pexels-photo-5886041.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    title: 'SHIRT STYLE!',
  },
  {
    id: 2,
    img: 'https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    title: 'LOUNGEWEAR LOVE',
  },
  {
    id: 3,
    img: 'https://images.pexels.com/photos/5480696/pexels-photo-5480696.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
    title: 'LIGHT JACKETS',
  },
];

export const popularProducts = [
  {
    id: 1,
    img: 'https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png',
  },
  {
    id: 2,
    img: '/Images/joggers.png',
  },
  {
    id: 3,
    img: 'https://www.prada.com/content/dam/pradanux_products/U/UCS/UCS319/1YOTF010O/UCS319_1YOT_F010O_S_182_SLF.png',
  },
  {
    id: 4,
    img: '/Images/sweat_shirt.png',
  },
  {
    id: 5,
    img: 'https://images.ctfassets.net/5gvckmvm9289/3BlDoZxSSjqAvv1jBJP7TH/65f9a95484117730ace42abf64e89572/Noissue-x-Creatsy-Tote-Bag-Mockup-Bundle-_4_-2.png',
  },
  {
    id: 6,
    img: 'https://d3o2e4jr3mxnm3.cloudfront.net/Rocket-Vintage-Chill-Cap_66374_1_lg.png',
  },
  {
    id: 7,
    img: '/Images/short_shirt.png',
  },
  {
    id: 8,
    img: 'https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png',
  },
];

export const allProducts = [
  {
    id: 1,
    img: 'https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png',
    title: 'Vintage Guitar Tee',
    desc: 'Classic vintage-inspired t-shirt featuring a guitar design.',
    rating: 4.8,
    numRatings: 150,
    price: '$29.99',
    discount: '15% off',
    update: 'Last updated 3 days ago',
  },
  {
    id: 2,
    img: '/Images/joggers.png',
    title: 'Comfort Joggers',
    desc: 'Stay comfortable and stylish with these versatile jogger pants.',
    rating: 4.5,
    numRatings: 120,
    price: '$39.99',
    discount: '10% off',
    update: 'Last updated 1 week ago',
  },
  {
    id: 3,
    img: 'https://www.prada.com/content/dam/pradanux_products/U/UCS/UCS319/1YOTF010O/UCS319_1YOT_F010O_S_182_SLF.png',
    title: 'Luxury Leather Handbag',
    desc: 'Elevate your style with this exquisite leather handbag from Prada.',
    rating: 4.9,
    numRatings: 200,
    price: '$599.99',
    discount: 'Free shipping',
    update: 'Last updated 2 days ago',
  },
  {
    id: 4,
    img: '/Images/sweat_shirt.png',
    title: 'Cozy Sweatshirt',
    desc: 'Perfect for chilly evenings, this cozy sweatshirt is a must-have.',
    rating: 4.7,
    numRatings: 180,
    price: '$49.99',
    discount: '20% off',
    update: 'Last updated 4 days ago',
  },
  {
    id: 5,
    img: 'https://images.ctfassets.net/5gvckmvm9289/3BlDoZxSSjqAvv1jBJP7TH/65f9a95484117730ace42abf64e89572/Noissue-x-Creatsy-Tote-Bag-Mockup-Bundle-_4_-2.png',
    title: 'Eco-Friendly Tote Bag',
    desc: 'Make a statement with this eco-friendly and stylish tote bag.',
    rating: 4.6,
    numRatings: 160,
    price: '$19.99',
    discount: 'Buy 1, Get 1 50% off',
    update: 'Last updated 5 days ago',
  },
  {
    id: 6,
    img: 'https://d3o2e4jr3mxnm3.cloudfront.net/Rocket-Vintage-Chill-Cap_66374_1_lg.png',
    title: 'Vintage Chill Cap',
    desc: 'Top off your look with this cool vintage-inspired chill cap.',
    rating: 4.8,
    numRatings: 170,
    price: '$24.99',
    discount: '15% off',
    update: 'Last updated 3 days ago',
  },
  {
    id: 7,
    img: '/Images/short_shirt.png',
    title: 'Short Sleeve Shirt',
    desc: 'Stay casual and comfortable with this stylish short sleeve shirt.',
    rating: 4.5,
    numRatings: 140,
    price: '$34.99',
    discount: '10% off',
    update: 'Last updated 6 days ago',
  },
  {
    id: 8,
    img: 'https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png',
    title: "Fashionable Women's Jacket",
    desc: "Step out in style with this fashionable women's jacket.",
    rating: 4.9,
    numRatings: 190,
    price: '$79.99',
    discount: 'Free shipping',
    update: 'Last updated 1 day ago',
  },
  {
    id: 9,
    img: 'https://www.pngitem.com/pimgs/m/166-1667033_mens-png-hd-men-png-transparent-png.png',
    title: "Casual Men's Shirt",
    desc: "Upgrade your wardrobe with this comfortable and trendy men's shirt.",
    rating: 4.6,
    numRatings: 130,
    price: '$44.99',
    discount: '20% off',
    update: 'Last updated 5 days ago',
  },
];
